# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
     
    - name: build
      run: npm build
    - name: deploy
      run: |
        git config --global user.email "tsaimouli1999@gmail.com"
        git config --global user.name "sachmo99"
        git remote set-url origin https://${{ secrets.AUTH_TOKEN }}@github.com/sachmo99/sequizapp.git
        npm run deploy
      
      
  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        CI: true
