# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      uses: actions/npm@master
      with:
        args: install -y
    - name: build
      uses: actions/npm@master
      with:
        args: run build
    - name: deploy
      run: |
        git config --global user.email "tsaimouli1999@gmail.com"
        git config --global user.name "sachmo99"
        git remote set-url origin https://962f87299c978266a33d739c68430c56cfe2e85f@github.com/sachmo99/sequizapp.git
        npm run deploy
      
      
  
      env:
        CI: true
